# Generated by Django 5.0.7 on 2024-07-20 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0002_facilities_order_trip_ticket_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='facilities',
            field=models.ManyToManyField(related_name='buses', to='station.facilities'),
        ),
    ]
